#!/bin/bash
################################################################################
#
#  Copyright (C) 2008, 2018 SES ENGINEERING, Luxembourg S.A.R.L.
#
#  This file is part of SPELL.
#
#  SPELL is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  SPELL is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with SPELL. If not, see <http://www.gnu.org/licenses/>.
#
################################################################################

#===============================================================================
# Setup main environment variables
#===============================================================================

# SPELL home
if [ -z $SPELL_HOME ]; then
    export SPELL_HOME=/home/spell/SPELL
fi
[ ! -d $SPELL_HOME ] && echo "ERROR: cannot find SPELL home directory: $SPELL_HOME" && exit 1

#===============================================================================
# Setup environment
#===============================================================================
SETUP_SCRIPT=$SPELL_HOME/bin/setup-environment.sh
[ ! -f $SETUP_SCRIPT ] && echo "ERROR: cannot find SPELL environment setup script: $SETUP_SCRIPT" && exit 1
! source $SETUP_SCRIPT && echo "ERROR: SPELL environment setup failed" && exit 1

$SPELL_HOME/bin/SPELL-Shell $@
